import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import RegisterServiceWorker from "./register-sw";

const noto = Noto_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "JITU - Pencatatan dan Analisis Bisnis Anda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#FFCA40" />
      </head>
      <body className={`${noto.className} antialiased`}>
        {children}
        <RegisterServiceWorker />
      </body>
    </html>
  );
}