import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import RegisterServiceWorker from "./register-sw";
import RouteLoadingOverlay from "@/components/partials/RouteLoadingOverlay";

const noto = Noto_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "JITU - Pencatatan dan Analisis Bisnis Anda",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover"
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#FFCA40" />
      </head>
      <body className={`${noto.className} antialiased`}>
        {children}
        <RouteLoadingOverlay />
        <RegisterServiceWorker />
      </body>
    </html>
  );
}
